name: Static Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.15.x'

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DMSVC_RUNTIME_LIBRARY="MultiThreaded"

    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      # Using -static flag for linker
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DCMAKE_EXE_LINKER_FLAGS="-static"

    - name: Build
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: engine-${{ matrix.os }}
        path: |
          build/Release/engine.exe
          build/engine
